name: Validate JSONs

on: [push]

jobs:
  verify-json-validation-overlay:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /schema.json
          INPUT_JSONS: /all.json
